on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Déploiement du projet"
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le projet
        uses: actions/checkout@v2
      - name: version de Java
        uses: action/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: générer le livrable
        run: |
          ls -al
          ./mvnw clean-package spring-boot:repackage -Dmaven.test.skip=true
          ls -al target

